/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"

void delay(void){

	for(volatile int i = 0; i < 500000; i++);
}



int main(void)
{
	GPIOA_CLK_EN();   // Enable clock for GPIOA

	//set PA5 as output (MODERS = 01)
    GPIOA->MODER &= ~(3 << (5*2));
    GPIOA->MODER |=  (1 << (5*2));     // PA5 output

    //push-pull
    GPIOA->OTYPER &= ~(1 << 5);

    //medium speed
    GPIOA->OSPEEDR |= (1 << (5*2));

    // No pull=up, pull-down
    GPIOA->PUPDR &= ~(3 << (5*2));



    while(1)
    {
        GPIOA->ODR ^= (1 << 5);            //  toggle LED
        delay();

    }
}
