/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f4xx.h>
#include <stdio.h>
#define LED_PIN  5
#define BUTTON_PIN   13



int main(void)
{
	GPIOA_CLK_EN();   // Enable clock for GPIOA
	GPIOC_CLK_EN();   // Enable clock for GPIOC


	//set PA5 as output (MODERS = 01)
    GPIOA->MODER &= ~(0x3 << (LED_PIN*2));
    GPIOA->MODER |=  (0x1 << (LED_PIN*2));     // PA5 output

    //set input button pin (MODER = 00)
    GPIOC->MODER &= ~(0x3 << (BUTTON_PIN*2));

    //push-pull
    GPIOA->OTYPER &= ~(0x1 << LED_PIN);

    //medium speed
    GPIOA->OSPEEDR |= (0x1 << (LED_PIN*2));

    // No pull=up, pull-down(00)
    GPIOA->PUPDR &= ~(0x3 << (LED_PIN*2));

    //pull-up (01)
    GPIOC->PUPDR &= ~(0x3 << (LED_PIN*2));
    GPIOC->PUPDR |= (0x3 << (LED_PIN*2));




    while(1)
    {
    	if(!(GPIOC->IDR & (1 << BUTTON_PIN))){
    	     GPIOA->ODR |= (1 << 5);            //  LED ON


    	}
    	else{
    	     GPIOA->ODR &= ~(1 << 5);            //  LED OFF
    	     printf("button is released");

    	}

    	}



    }
