/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include <stdint.h>
#include <stdio.h>
#include <stm32f4xx.h>

extern void initialise_monitor_handles();
#define ADC1_PIN 0
void adc_init(void);
uint16_t adc_read(void);

int main(void)
{
	initialise_monitor_handles();
	uint16_t adc;
	float temp;
	adc_init();


	while(1)
	{
		adc = adc_read();
		temp = (adc*3.3f/4095.0f)*100.0f;
		 printf("Temperature = %.2f C\n",temp);

		 for(volatile int i=0; i<5000000; i++);
	}
}
	void adc_init(void)
	{
		GPIOA_CLK_EN();

		ADC1_CLK_EN();


		GPIOA->MODER |= (3 << (ADC1_PIN*2));
		GPIOA->PUPDR &= ~(3 << (ADC1_PIN*2));

		ADC1->CR2 |= (1 << 10);

		ADC1->SQR3 |= ADC1_PIN;
		ADC1->SMPR2 |= (3 << 0);
		ADC1->CR2 |= (1 << 0);

	}

	uint16_t adc_read(void)
	{
		ADC1->CR2 |= (1 << 30);

		while(!(ADC1->SR & (1 << 1)));
		uint16_t adc_reading = ADC1->DR;
		 return adc_reading;


}
